fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

twitch_page_admin:
    resource: "@TwitchPageAdminBundle/Resources/config/routing.yml"
    prefix:   /

twicth_page:
    resource: "@TwitchPageBundle/Resources/config/routing.yml"
    prefix:   /
